#!/bin/bash

usage()
{
    echo $program: invocation error >&2
    exit 1
}

me="&contact=pgf@foxharp.boston.ma.us"

# doit=echo

program=${0##*/}

: args: $*

server="www.overpass-api.de/api/xapi?*"
#server="overpass.osm.rambler.ru/cgi/xapi?*"


if ! opts="$(getopt -o b:B:x: \
	-l bits:,bbox:,xmlfile: -n $program -- $@)"
then
    usage
fi

eval set -- "$opts"

xmlfile="-"

while true
do
    : \$1 is $1
    case $1 in
	-b|--bits) bits=$2; shift 2 ;;
	-B|--bbox) bbox=$2; shift 2 ;;
	-x|--xmlfile) xmlfile=$2; shift 2 ;;
	--) shift; break ;;
	*) usage ;;
    esac
done

bbox="[bbox=$bbox]"

trap "rm -f $xmlfile.tmp" 0

if [ -e $xmlfile ]
then
    echo Already have $xmlfile
    exit
fi

# normally the .osm.gz files are stored alongside the .rdm files.
# but for development, it can be convenient to be able to get the .osm from
# somewhere else on the local system.
localstore=/usr/local/share/roadmap/newquads

# isolate the qt19/.../file.osm.gz partial path
wantqtpath=qt$bits/${xmlfile##*/qt$bits}

if [ -e "$localstore/$wantqtpath" ]
then
    mkdir -p $(dirname $xmlfile)
    cp $localstore/$wantqtpath $xmlfile
    exit
fi

# okay... we need to get it from the web.
# one or two more layers of caching would be nice here -- a web
# cache of .osm.gz files is an obvious thing (to avoid all the
# clipping and slow transfer from the OSM servers), and maybe
# even a web store of .rdm files -- but that should really be
# checked long before we get to this point.

case $xmlfile in
*.gz) want_compressed=1 ;;
esac

url="http://$server$bbox$query$me"

echo "Fetching from $url"

if [ "$want_compressed" ]
then
    wget_opt="--header=Accept-Encoding: gzip"
    if wget "$wget_opt" -O - "$url" >$xmlfile.tmp
    then
	case $(file $xmlfile.tmp) in
	*gzip*)
	    mv $xmlfile.tmp $xmlfile
	    ;;
	*)
	    echo "Note: download didn't use gzip encoding."
	    echo "Compressing now..."
	    gzip -c -d $xmlfile.tmp > $xmlfile
	    ;;
	esac
    fi
else
    if wget $wget_opt -O - "$url" >$xmlfile.tmp
    then
	mv $xmlfile.tmp $xmlfile
    fi
fi

