#!/bin/sh

usage()
{
    echo $program: invocation error >&2
    exit 1
}

me="&contact=pgf@foxharp.boston.ma.us"

# doit=echo

program=${0##*/}

: args: $*

#server="www.overpass-api.de/api/xapi?*"
server="overpass.osm.rambler.ru/cgi/xapi?*"


if ! opts="$(getopt -o t:b:h:B:x: \
	-l trutile:,bits:,have:,bbox:,xmlfile: -n $program -- $@)"
then
    usage
fi

eval set -- "$opts"

xmlfile="-"

while true
do
    : \$1 is $1
    case $1 in
	-t|--trutile) trutile=$2; shift 2 ;;
	-h|--have) have=$2; shift 2 ;;
	-b|--bits) bits=$2; shift 2 ;;
	-B|--bbox) bbox=$2; shift 2 ;;
	-x|--xmlfile) xmlfile=$2; shift 2 ;;
	--) shift; break ;;
	*) usage ;;
    esac
done

bbox="[bbox=$bbox]"

case $xmlfile in
*.gz)	pipe="gzip -c" ;;
*)	pipe="cat" ;;
esac

if [ -e $xmlfile ]
then
    echo Already have $xmlfile
elif wget -O - "http://$server$bbox$query$me" | $pipe >$xmlfile.tmp 
then
    mv $xmlfile.tmp $xmlfile
else
    rm $xmlfile.tmp
fi
